name: 'Run esmini'
description: 'An action script that will perform simulations using the 
              open-source scenario simulator esmini'
inputs:
  xosc: 
    description: 'Path to the OpenSCENARIO file that shall be simulated
                  Example: "./path/to/scenario.xosc"'
    required: true
  parameter-variation:
    description: 'Optionally a parameter distribution file, according to
                  the OpenSCENARIO standard can be set.
                  Example: "./path/to/parameter_set.xosc"'
    required: false
  release:
    description: 'Optionally, the name of the esmini release can be determined
                  by indicating the according tag.
                  Please note: Make sure to define the "asset" input to make
                  sure the installation will succeed!
                  Example: "v2.33.2"'                  
    required: false
    default: 'v2.36.2'
  asset:
    description: 'If a specific relase is determined, the asset of the relase 
                  to install must be determined as well.
                  Example: "esmini-bin_Linux.zip"'
    required: false
    default: 'esmini-bin_Linux.zip'
  token:
    description: 'Github token (required to download esmini release). For ease 
                  of use, I recommend to use the automatically created token of
                  your workflow, accessible via the secrets.GITHUB_TOKEN env
                  variable.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y unzip
    - name: Download release
      shell: bash
      run: gh release download ${{ inputs.release }} --repo https://github.com/esmini/esmini --pattern ${{ inputs.asset }}
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: unzip release
      shell: bash
      run: unzip ${{ inputs.asset }}
    - name: run simulation
      shell: bash
      run: |
        esminiExec=$(find -wholename "**/bin/esmini")
        parameterVariationFile=${{ inputs.parameter-variation }}
        if [ -n $parameterVariationFile ]
          then
            $esminiExec --headless --osc ${{ inputs.xosc }} --param_dist ${{ inputs.parameter-variation }}
          else
            $esminiExec --headless --osc ${{ inputs.xosc }}
          fi
        fi